language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer install --no-interaction

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then vendor/bin/codecept run unit --coverage-xml; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then vendor/bin/codecept run unit; fi;

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi;


notifications:
  irc: "irc.freenode.org#fuelphp-status"
