language: php

php:
  - 5.4
  - 5.5

before_script:
  - chmod -R 777 resources
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#fuelphp-status"
